--------------------------------------------------------
--  1. DDL for Table CHILD
--------------------------------------------------------


  CREATE TABLE "KIDSBANK"."CHILD" 
   (	"CHILD_NUM" NUMBER, 
	"ID" VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(60 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"JOIN_DATE" DATE, 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"REGISTRATION_NUMBER" VARCHAR2(20 BYTE), 
	"IS_OPEN" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHILD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."CHILD_PK" ON "KIDSBANK"."CHILD" ("CHILD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHILD_ID_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."CHILD_ID_UK" ON "KIDSBANK"."CHILD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHILD_NICKNAME_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."CHILD_NICKNAME_UK" ON "KIDSBANK"."CHILD" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CHILD
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."CHILD" ADD CONSTRAINT "CHILD_NICKNAME_UK" UNIQUE ("NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."CHILD" ADD CONSTRAINT "CHILD_ID_UK" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."CHILD" ADD CONSTRAINT "CHILD_PK" PRIMARY KEY ("CHILD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."CHILD" MODIFY ("REGISTRATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."CHILD" MODIFY ("JOIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."CHILD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."CHILD" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."CHILD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."CHILD" MODIFY ("CHILD_NUM" NOT NULL ENABLE);
  
  
  --------------------------------------------------------
-- 2. DDL for Table PARENT
--------------------------------------------------------

  CREATE TABLE "KIDSBANK"."PARENT" 
   (	"PARENT_NUM" NUMBER, 
	"ID" VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(60 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"JOIN_DATE" DATE, 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"PARENT_TYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."TABLE1_PK" ON "KIDSBANK"."PARENT" ("PARENT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARENT_ID_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."PARENT_ID_UK" ON "KIDSBANK"."PARENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARENT_NICKNAME_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."PARENT_NICKNAME_UK" ON "KIDSBANK"."PARENT" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PARENT
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."PARENT" ADD CONSTRAINT "PARENT_NICKNAME_UK" UNIQUE ("NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."PARENT" ADD CONSTRAINT "PARENT_ID_UK" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."PARENT" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("PARENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."PARENT" MODIFY ("PARENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT" MODIFY ("JOIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT" MODIFY ("PARENT_NUM" NOT NULL ENABLE);
  
  --------------------------------------------------------
-- 3. DDL for Table PARENT_CHILD
--------------------------------------------------------

  CREATE TABLE "KIDSBANK"."PARENT_CHILD" 
   (	"PARENT_CHILD_NUM" NUMBER, 
	"CHILD_NUM" NUMBER, 
	"PARENT_NUM" NUMBER, 
	"CHILD_ORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARENT_CHILD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."PARENT_CHILD_PK" ON "KIDSBANK"."PARENT_CHILD" ("PARENT_CHILD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PARENT_CHILD
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."PARENT_CHILD" ADD CONSTRAINT "PARENT_CHILD_PK" PRIMARY KEY ("PARENT_CHILD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" MODIFY ("CHILD_ORDER" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" MODIFY ("PARENT_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" MODIFY ("CHILD_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" MODIFY ("PARENT_CHILD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PARENT_CHILD
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."PARENT_CHILD" ADD CONSTRAINT "FK_CHILD_NUM" FOREIGN KEY ("CHILD_NUM")
	  REFERENCES "KIDSBANK"."CHILD" ("CHILD_NUM") ENABLE;
  ALTER TABLE "KIDSBANK"."PARENT_CHILD" ADD CONSTRAINT "FK_PARENT_NUM" FOREIGN KEY ("PARENT_NUM")
	  REFERENCES "KIDSBANK"."PARENT" ("PARENT_NUM") ENABLE;
      
--------------------------------------------------------
-- 4. DDL for Table MONEY_BOOK
--------------------------------------------------------

  CREATE TABLE "KIDSBANK"."MONEY_BOOK" 
   (	"MONEY_BOOK_NUM" NUMBER, 
	"CHILD_NUM" NUMBER, 
	"MONEY_TYPE" NUMBER, 
	"OUTCOME_TYPE" NUMBER, 
	"AMOUNT" NUMBER, 
	"CONTENT" VARCHAR2(100 BYTE), 
	"MEMO" VARCHAR2(200 BYTE), 
	"MONEY_DATE" DATE, 
	"WRITE_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MONEY_BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."MONEY_BOOK_PK" ON "KIDSBANK"."MONEY_BOOK" ("MONEY_BOOK_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MONEY_BOOK
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."MONEY_BOOK" ADD CONSTRAINT "MONEY_BOOK_PK" PRIMARY KEY ("MONEY_BOOK_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("MONEY_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("OUTCOME_TYPE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("MONEY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("CHILD_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."MONEY_BOOK" MODIFY ("MONEY_BOOK_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MONEY_BOOK
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."MONEY_BOOK" ADD CONSTRAINT "FK_MONEY_BOOK_CHILD_NUM" FOREIGN KEY ("CHILD_NUM")
	  REFERENCES "KIDSBANK"."CHILD" ("CHILD_NUM") ENABLE;
      
--------------------------------------------------------
-- 5. DDL for Table EMOJI
--------------------------------------------------------

  CREATE TABLE "KIDSBANK"."EMOJI" 
   (	"PARENT_NUM" NUMBER, 
	"CHILD_NUM" NUMBER, 
	"EMOJI_TYPE" NUMBER, 
	"MONEY_DATE" DATE, 
	"WRITE_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMOJI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."EMOJI_PK" ON "KIDSBANK"."EMOJI" ("PARENT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMOJI
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."EMOJI" ADD CONSTRAINT "EMOJI_PK" PRIMARY KEY ("PARENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."EMOJI" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."EMOJI" MODIFY ("MONEY_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."EMOJI" MODIFY ("CHILD_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."EMOJI" MODIFY ("PARENT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMOJI
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."EMOJI" ADD CONSTRAINT "FK_EMOJI_CHILD_NUM" FOREIGN KEY ("CHILD_NUM")
	  REFERENCES "KIDSBANK"."CHILD" ("CHILD_NUM") ENABLE;
      
--------------------------------------------------------
-- 6. DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "KIDSBANK"."COMMENTS" 
   (	"COMMENTS_NUM" NUMBER, 
	"CHILD_NUM" NUMBER, 
	"PARENT_NUM" NUMBER, 
	"CONTENT" VARCHAR2(100 BYTE), 
	"MONEY_DATE" DATE, 
	"WRITE_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."COMMENTS_PK" ON "KIDSBANK"."COMMENTS" ("COMMENTS_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_CHILD_NUM_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."COMMENTS_CHILD_NUM_UK" ON "KIDSBANK"."COMMENTS" ("CHILD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_PARENT_NUM_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIDSBANK"."COMMENTS_PARENT_NUM_UK" ON "KIDSBANK"."COMMENTS" ("PARENT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."COMMENTS" ADD CONSTRAINT "COMMENTS_PARENT_NUM_UK" UNIQUE ("PARENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."COMMENTS" ADD CONSTRAINT "COMMENTS_CHILD_NUM_UK" UNIQUE ("CHILD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("COMMENTS_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KIDSBANK"."COMMENTS" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."COMMENTS" MODIFY ("MONEY_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."COMMENTS" MODIFY ("PARENT_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."COMMENTS" MODIFY ("CHILD_NUM" NOT NULL ENABLE);
  ALTER TABLE "KIDSBANK"."COMMENTS" MODIFY ("COMMENTS_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "KIDSBANK"."COMMENTS" ADD CONSTRAINT "COMMENTS_CHILD_NUM_FK" FOREIGN KEY ("CHILD_NUM")
	  REFERENCES "KIDSBANK"."CHILD" ("CHILD_NUM") ENABLE;
  ALTER TABLE "KIDSBANK"."COMMENTS" ADD CONSTRAINT "COMMENTS_PARENT_NUM_FK" FOREIGN KEY ("PARENT_NUM")
	  REFERENCES "KIDSBANK"."PARENT" ("PARENT_NUM") ENABLE;
      
      